apiVersion: v1
kind: Service
metadata:
  name: ping-server
spec:
  selector:
    app: ping-server
  type: LoadBalancer # NodePort / ClusterIP / LoadBalancer
  ports:
    - name: http
      port: 8081
      targetPort: 8081
